<a href="https://www.kaggle.com/code/samiaakterkeya/mlb-2-samia?scriptVersionId=346739103" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [66]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [67]:
import numpy as np
import pandas as pd

In [68]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [69]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [70]:
#1D 
x=np.array([25,35,45])
x

array([25, 35, 45])

In [71]:
#2D
y=np.array([[25,35,45],[23,24,35]])
y

array([[25, 35, 45],
       [23, 24, 35]])

In [72]:
#3D
z=np.array([[[12,13,14],[15,24,35]],[[36,34,56],[2,3,4]]])
z

array([[[12, 13, 14],
        [15, 24, 35]],

       [[36, 34, 56],
        [ 2,  3,  4]]])

In [73]:
#4D
p=np.array([[[[1,2,3],[3,4,5]],[[4,5,6],[2,5,7]]]])
p

array([[[[1, 2, 3],
         [3, 4, 5]],

        [[4, 5, 6],
         [2, 5, 7]]]])

# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [74]:
#1D
x=np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [75]:
#2D
y=np.arange(1,9).reshape(2,4)
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
#3D
z=np.arange(1,17).reshape(4,2,2)
z

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [77]:
#4D
p=np.arange(1,25).reshape(3,2,2,2)
p

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])

# create array using ones and zeros

In [78]:
x=np.ones((3,2),dtype=int)
x

array([[1, 1],
       [1, 1],
       [1, 1]])

In [79]:
y=np.zeros((5,6),dtype=int)
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# using random

In [80]:
#only random use , value will be 0<= value >1
x= np.random.random((3,4)) 
x


array([[0.10397771, 0.2351858 , 0.75303486, 0.9287276 ],
       [0.02603363, 0.69612774, 0.01161353, 0.97734724],
       [0.77603256, 0.67452934, 0.39891801, 0.21133933]])

In [82]:
#using round 
y= np.round(np.random.random((3,4)))
y

array([[0., 1., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

In [83]:
#take values withiin 0 to 100
z= np.round(np.random.random((3,4))*100)
z

array([[39., 71., 94., 28.],
       [97., 31.,  4.,  3.],
       [36., 97.,  4., 29.]])

# using linspace

In [84]:
w=np.linspace(50,150,10, dtype=int)
w

array([ 50,  61,  72,  83,  94, 105, 116, 127, 138, 150])

# create 1D array of tip from tips dataframe

In [85]:
Tip=tips['tip'].to_numpy()
print(Tip)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

# create 2D array of tip and total_bill form tips dataframe

In [86]:
Total=tips[['tip','total_bill']].to_numpy()
Total

array([[ 1.01, 16.99],
       [ 1.66, 10.34],
       [ 3.5 , 21.01],
       [ 3.31, 23.68],
       [ 3.61, 24.59],
       [ 4.71, 25.29],
       [ 2.  ,  8.77],
       [ 3.12, 26.88],
       [ 1.96, 15.04],
       [ 3.23, 14.78],
       [ 1.71, 10.27],
       [ 5.  , 35.26],
       [ 1.57, 15.42],
       [ 3.  , 18.43],
       [ 3.02, 14.83],
       [ 3.92, 21.58],
       [ 1.67, 10.33],
       [ 3.71, 16.29],
       [ 3.5 , 16.97],
       [ 3.35, 20.65],
       [ 4.08, 17.92],
       [ 2.75, 20.29],
       [ 2.23, 15.77],
       [ 7.58, 39.42],
       [ 3.18, 19.82],
       [ 2.34, 17.81],
       [ 2.  , 13.37],
       [ 2.  , 12.69],
       [ 4.3 , 21.7 ],
       [ 3.  , 19.65],
       [ 1.45,  9.55],
       [ 2.5 , 18.35],
       [ 3.  , 15.06],
       [ 2.45, 20.69],
       [ 3.27, 17.78],
       [ 3.6 , 24.06],
       [ 2.  , 16.31],
       [ 3.07, 16.93],
       [ 2.31, 18.69],
       [ 5.  , 31.27],
       [ 2.24, 16.04],
       [ 2.54, 17.46],
       [ 3.06, 13.94],
       [ 1.

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [87]:
#Check dimention
x=np.array([1,2,35,6])
print(x.ndim)

y=np.array([[[1,2,3],[5,7,8],],[[2,3,7],[2,6,7]]])
print(y.ndim)


1
3


In [88]:
#Shape
p=x.shape

z=y.shape
print(p)
print(z)


(4,)
(2, 2, 3)


In [89]:
n= np.size(x)
m=np.size(y)
print(n)
print(m)

4
12


In [90]:
q=x.itemsize
r=y.itemsize
print(f'q:{x}\n')

print(f'r:{y}\n')

q:[ 1  2 35  6]

r:[[[1 2 3]
  [5 7 8]]

 [[2 3 7]
  [2 6 7]]]



# change data type and memory size of any np-array using astype()

In [91]:
x=np.array([5,4,9,10])
print(x)
print(x.dtype)
print(x.itemsize)

#change data type and memory size
print("After change:\n")
y=x.astype(np.float32)
print(y)
print(y.dtype)
print(y.itemsize)

[ 5  4  9 10]
int64
8
After change:

[ 5.  4.  9. 10.]
float32
4


# create 2 same dimensional array and do scalar and vector operations

In [92]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(3,9).reshape(2,3)
print(f"a:{a}\n")
print(f"b:{b}\n")


a:[[1 2 3]
 [4 5 6]]

b:[[3 4 5]
 [6 7 8]]



In [93]:
#scalar
print(f"a:{a+2}\n")
print(f"b:{b**2}\n")

a:[[3 4 5]
 [6 7 8]]

b:[[ 9 16 25]
 [36 49 64]]



In [94]:
#vactor
c=a+b
print(f"add:{c}")
d=b-a
print(f"sub:{d}")

add:[[ 4  6  8]
 [10 12 14]]
sub:[[2 2 2]
 [2 2 2]]


# find minimun and maximum tip

In [95]:
#min column
print(f"min:{np.min(Tip,axis=0)}")

min:1.0


In [96]:
#max column
print(f"max:{np.max(Tip,axis=0)}")

max:10.0


# find average total_bill and average tip

In [97]:
print(f"Avarage of total bill:{np.mean(tips['total_bill']):.2f}")


Avarage of total bill:19.79


In [98]:
print(f"Avarage of tip:{np.mean(tips['tip']):.2f}")

Avarage of tip:3.00


# find median total_bill

In [99]:
print(f"Median of total bill:{np.median(tips['total_bill']):.2f}")

Median of total bill:17.80


# find standard deviasion and variance of tip

In [100]:
print(f"standard deviasion:{np.std(tips['tip']):.2f}")

standard deviasion:1.38


In [101]:
print(f"variance :{np.var(tips['tip']):.2f}")

variance :1.91


# find log values of tip

In [102]:
np.log(tips['tip'])

0      0.009950
1      0.506818
2      1.252763
3      1.196948
4      1.283708
         ...   
239    1.778336
240    0.693147
241    0.693147
242    0.559616
243    1.098612
Name: tip, Length: 244, dtype: float64

# apply round, floor and ceil operation on tip array

In [103]:
np.round(Tip)

array([ 1.,  2.,  4.,  3.,  4.,  5.,  2.,  3.,  2.,  3.,  2.,  5.,  2.,
        3.,  3.,  4.,  2.,  4.,  4.,  3.,  4.,  3.,  2.,  8.,  3.,  2.,
        2.,  2.,  4.,  3.,  1.,  2.,  3.,  2.,  3.,  4.,  2.,  3.,  2.,
        5.,  2.,  3.,  3.,  1.,  6.,  3.,  5.,  6.,  2.,  3.,  2.,  3.,
        5.,  2.,  4.,  4.,  3.,  2.,  2.,  7.,  3.,  2.,  2.,  4.,  3.,
        3.,  2.,  1.,  2.,  2.,  2.,  3.,  3.,  5.,  2.,  1.,  3.,  4.,
        3.,  3.,  3.,  3.,  2.,  5.,  2.,  5.,  2.,  4.,  6.,  3.,  3.,
        4.,  1.,  4.,  3.,  5.,  4.,  2.,  3.,  2.,  2.,  3.,  2.,  3.,
        4.,  2.,  4.,  4.,  4.,  4.,  3.,  1.,  4.,  3.,  4.,  4.,  5.,
        2.,  2.,  3.,  2.,  2.,  2.,  2.,  3.,  4.,  1.,  2.,  2.,  2.,
        2.,  3.,  2.,  2.,  3.,  1.,  2.,  2.,  2.,  3.,  4.,  7.,  5.,
        5.,  2.,  2.,  1.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,  2.,  5.,
        5.,  4.,  3.,  2.,  4.,  2.,  2.,  2.,  3.,  3.,  2.,  4.,  2.,
        2., 10.,  3.,  5.,  3.,  4.,  3.,  2.,  2.,  4.,  4.,  4

In [104]:
np.floor(Tip)

array([ 1.,  1.,  3.,  3.,  3.,  4.,  2.,  3.,  1.,  3.,  1.,  5.,  1.,
        3.,  3.,  3.,  1.,  3.,  3.,  3.,  4.,  2.,  2.,  7.,  3.,  2.,
        2.,  2.,  4.,  3.,  1.,  2.,  3.,  2.,  3.,  3.,  2.,  3.,  2.,
        5.,  2.,  2.,  3.,  1.,  5.,  3.,  5.,  6.,  2.,  3.,  2.,  2.,
        5.,  1.,  4.,  3.,  3.,  1.,  1.,  6.,  3.,  2.,  1.,  3.,  2.,
        3.,  2.,  1.,  2.,  2.,  1.,  3.,  3.,  5.,  2.,  1.,  3.,  4.,
        3.,  2.,  3.,  3.,  1.,  5.,  2.,  5.,  2.,  4.,  5.,  3.,  3.,
        3.,  1.,  4.,  3.,  4.,  4.,  1.,  3.,  1.,  2.,  3.,  2.,  3.,
        4.,  1.,  4.,  4.,  3.,  4.,  3.,  1.,  4.,  2.,  4.,  3.,  5.,
        1.,  1.,  2.,  2.,  1.,  2.,  2.,  2.,  4.,  1.,  2.,  2.,  2.,
        1.,  2.,  1.,  2.,  3.,  1.,  2.,  2.,  2.,  2.,  3.,  6.,  5.,
        5.,  2.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  5.,
        5.,  3.,  2.,  2.,  3.,  2.,  2.,  2.,  3.,  3.,  2.,  4.,  1.,
        2., 10.,  3.,  5.,  3.,  4.,  3.,  2.,  2.,  4.,  3.,  3

In [105]:
np.ceil(Tip)

array([ 2.,  2.,  4.,  4.,  4.,  5.,  2.,  4.,  2.,  4.,  2.,  5.,  2.,
        3.,  4.,  4.,  2.,  4.,  4.,  4.,  5.,  3.,  3.,  8.,  4.,  3.,
        2.,  2.,  5.,  3.,  2.,  3.,  3.,  3.,  4.,  4.,  2.,  4.,  3.,
        5.,  3.,  3.,  4.,  2.,  6.,  3.,  5.,  6.,  3.,  3.,  3.,  3.,
        6.,  2.,  5.,  4.,  3.,  2.,  2.,  7.,  4.,  2.,  2.,  4.,  3.,
        4.,  3.,  1.,  3.,  3.,  2.,  3.,  4.,  5.,  3.,  2.,  4.,  4.,
        3.,  3.,  3.,  4.,  2.,  5.,  3.,  6.,  2.,  4.,  6.,  3.,  3.,
        4.,  1.,  5.,  4.,  5.,  4.,  2.,  3.,  2.,  3.,  3.,  3.,  4.,
        5.,  2.,  5.,  5.,  4.,  4.,  3.,  1.,  4.,  3.,  4.,  4.,  6.,
        2.,  2.,  3.,  3.,  2.,  3.,  2.,  3.,  5.,  2.,  2.,  2.,  3.,
        2.,  3.,  2.,  2.,  4.,  2.,  2.,  2.,  2.,  3.,  4.,  7.,  5.,
        5.,  3.,  2.,  2.,  2.,  2.,  2.,  3.,  2.,  3.,  2.,  2.,  6.,
        5.,  4.,  3.,  2.,  4.,  3.,  2.,  2.,  3.,  4.,  3.,  5.,  2.,
        2., 10.,  4.,  6.,  4.,  4.,  4.,  2.,  2.,  4.,  4.,  4

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [106]:
x=np.array([25,35,45])
y=np.array([[25,35,45],[23,24,35]])
z=np.array([[[12,13,14],[15,24,35]],[[36,34,56],[2,3,4]]])



In [107]:
#indexing
print(x[0])
print(x[-1])
print(y[0, 0])
print(y[1, 2])
print(z[1, 1, 2])

25
45
25
35
4


In [108]:
#slicing
print(x[0:2])
print(x[:2])
print(y[0, :])
print(y[:, 0])
print(z[0, :, :])

[25 35]
[25 35]
[25 35 45]
[25 23]
[[12 13 14]
 [15 24 35]]


# stacking and spliting

In [109]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)


In [110]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [111]:
e

array([[28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54]])

# use hstack() and vstack()

In [112]:
## connect horizontally
np.hstack((e,d))

array([[28, 29, 30, 31, 32, 33, 34, 35, 36,  0,  1,  2,  3,  4,  5,  6,
         7,  8],
       [37, 38, 39, 40, 41, 42, 43, 44, 45,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [46, 47, 48, 49, 50, 51, 52, 53, 54, 18, 19, 20, 21, 22, 23, 24,
        25, 26]])

In [113]:
## connect vertically
np.vstack((d,e,d))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

# use hsplit() and vsplit()

In [115]:
np.hsplit(d,3)

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]]),
 array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]]),
 array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]])]

In [116]:
np.vsplit(e,3)

[array([[28, 29, 30, 31, 32, 33, 34, 35, 36]]),
 array([[37, 38, 39, 40, 41, 42, 43, 44, 45]]),
 array([[46, 47, 48, 49, 50, 51, 52, 53, 54]])]